setup:
  - apt:
      - npm
      - wget
      - maven
      - nodejs
      - mysql-server
      - openjdk-11-jdk
  - url:
      - https://github.ncsu.edu/engr-csc326-staff/iTrust2-v10

jobs:
  - name: build-itrust
    steps:
      - name: iTrust2 mvn build
        run: cd iTrust2 && mvn --batch-mode --update-snapshots clean test
