setup:
  - { package: mysql, version: 8.0, param: $ENV_VAR_PRMTS }
  - apt-get install mysql -y
  - java11, nodejs, wget
  - URL=https://github.ncsu.edu/engr-csc326-staff/iTrust2-v10

jobs:
  - name: build-itrust
    steps:
      - name: iTrust2 mvn build
        run: cd iTrust2 && mvn --batch-mode --update-snapshots clean test
